services:
  backend-metrica:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend-metrica
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - PORT=3000
      - TZ=UTC
    expose:
      - "3000"

  terminal-metrica:
    image: tsl0922/ttyd:latest
    container_name: terminal-metrica
    restart: always
    # Eliminamos -i lo para que Nginx pueda conectar, y usamos 'sh' por compatibilidad
    command: ttyd -p 7681 -W sh
    environment:
      - TZ=UTC
    expose:
      - "7681"

  frontend-metrica:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend-metrica
    restart: always
    ports:
      - "4205:4200"
    environment:
      # Credenciales por defecto (C√ÅMBIALAS)
      - AUTH_USER=admin
      - AUTH_PASS=katrix2026
    depends_on:
      - backend-metrica
      - terminal-metrica
    networks:
      - default
      - npm_network

networks:
  npm_network:
    external: true
