services:
  katrix-monitor-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: katrix-monitor-backend
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - PORT=3000
      - TZ=UTC
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc
    deploy:
      resources:
        limits:
          memory: 100M
          cpus: '0.3'

  katrix-monitor-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: katrix-monitor-frontend
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - katrix-monitor-backend
    deploy:
      resources:
        limits:
          memory: 30M
          cpus: '0.2'
