services:
  backend-metrica:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend-metrica
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - PORT=3000
      - TZ=UTC
      - AUTH_PASS=katrix2026
    expose:
      - "3000"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          memory: 128M

  frontend-metrica:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend-metrica
    restart: always
    ports:
      - "4205:4200"
    depends_on:
      - backend-metrica
    networks:
      - default
      - npm_network
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 256M
        reservations:
          memory: 64M

networks:
  npm_network:
    external: true
