services:
  backend-metrica:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend-metrica
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - PORT=3000
      - TZ=UTC
    # Internal port for frontend to connect
    expose:
      - "3000"

  frontend-metrica:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend-metrica
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - backend-metrica
