services:
  katrix-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: katrix-monitor-lite
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    ports:
      - "3001:3000"
    # network_mode: "host" 
    deploy:
      resources:
        limits:
          memory: 150M
          cpus: '0.5'
    environment:
      - PORT=3000
      - TZ=UTC
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc
