services:
  katrix-monitor-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: katrix-api
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - PORT=3000
      - TZ=UTC

  katrix-monitor-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: katrix-web
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - katrix-monitor-backend
