services:
  katrix-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: katrix-monitor-lite
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - PORT=4200
      - TZ=UTC
    # No exponemos puertos al host si el proxy inverso ya usa el 4200.
    # El proxy lo encontrar√° por el nombre del servicio en la red de docker.
    expose:
      - "4200"
